name: Build (MSVC)

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7.0.0

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11.6

            - name: Configure CMake
              run: |
                  cmake -S . -B build/ `
                    -DCMAKE_BUILD_TYPE=Release `
                    -DVCPKG_TARGET_TRIPLET=x64-windows-static `
                    -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded `
                    -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

            - name: Build with CMake
              run: |
                  cmake --build build/ --config Release

            - name: Upload artifacts
              uses: actions/upload-artifact@v7.0.1
              with:
                  name: osproxy-msvc-x64-static
                  path: build/Release/osproxy.dll
